web/config/routes.rb
Tut1::Application.routes.draw do
  
  resources :families

  resources :products

  resources :discounts

  resources :sales

  resources :detail_sales

  get "index/home"

  root 'index#home'

  devise_for :users, path: '',
    path_names: {
      sign_in: 'login',
      sign_out: 'logout',
      password: 'reset_password'
    }
  get "users" => "users#index"
  get "profile" => "users#show", as: "current_user"
  get "profile/edit" => "users#edit", as: "edit_current_user"
  patch "profile" => "users#update", as: "user"

  namespace :api, defaults: {format: :json} do
    namespace :v1 do 

      post 'products/:id', to: 'products#create'
      get 'products/:id', to: 'products#show'
      get 'products', to: 'products#index'
      put 'products/:id', to: 'products#update'

      post 'discounts/:id', to: 'discounts#create'
      get 'discounts/:id', to: 'discounts#show'
      get 'discounts', to: 'discounts#index'
      put 'discounts/:id', to: 'discounts#update'

      post 'sales/:id', to: 'sales#create'
      get 'sales/:id', to: 'sales#show'
      get 'sales', to: 'sales#index'
      put 'sales/:id', to: 'sales#update'

      post 'detail_sales/:id', to: 'detail_sales#create'
      get 'detail_sales/:id', to: 'detail_sales#show'
      get 'detail_sales', to: 'detail_sales#index'
      put 'detail_sales/:id', to: 'detail_sales#update'
    end 
  end
  

end

web/app/models/family.rb
class Family < ActiveRecord::Base
	include Filterable
	include Importable
	include Exportable

	self.per_page = 10

		
	# Validations
			# validates :name, <validations>
			# validates :description, <validations>
	
	# Scopes (used for search form)
	#   To search by full text use { where("attribute like ?", "%#{attribute}%") }
	#   To search by string use { where attribute: attribute }
		scope :byname, -> (name) { where("name like ?", "%#{name}%") }
		scope :description, -> (description) { where description: description }
	
end

web/app/controllers/families_controller.rb
class FamiliesController < ApplicationController
  before_action :set_family, only: [:show, :edit, :update, :destroy]

  # GET /families
  def index
    @families = Family.paginate(:page => params[:page])
  end

  # GET /families/1
  def show
  end

  # GET /families/new
  def new
    @family = Family.new
  end

  # GET /families/1/edit
  def edit
  end

  # POST /families
  def create
    @family = Family.new(family_params)

    if @family.save
      redirect_to @family, notice: 'Family was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /families/1
  def update
    if @family.update(family_params)
      redirect_to @family, notice: 'Family was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /families/1
  def destroy
    @family.destroy
    redirect_to families_url, notice: 'Family was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_family
      @family = Family.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def family_params
      params.require(:family).permit(:name, :description)
    end
end

web/app/helpers/families_helper.rb
module FamiliesHelper
end

web/app/views/families/_form.html.erb
<%= form_for(@family) do |f| %>
<% if @family.errors.any? %>
<div id="error_explanation">
    <h2><%= pluralize(@family.errors.count, "error") %> prohibited this family from being saved:</h2>

    <ul>
        <% @family.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
    </ul>
</div>
<% end %>

<div class="form-group">
                <%= f.label :name %>
            <%= f.text_field :name, :class => "form-control" %>
    </div>
<div class="form-group">
                <%= f.label :description %>
            <%= f.text_field :description, :class => "form-control" %>
    </div>
<div class="actions">
    <%= f.submit :class => "btn btn-success" %>
</div>
<% end %>

web/app/views/families/edit.html.erb
<h1>Editing family</h1>
<hr>

<div class="panel panel-default">
	<div class="panel-heading panel-heading-toolbox">
		<div class="panel-toolbar">
			<%= link_to 'Volver', families_path, :class => "btn btn-link" %>
			<%= link_to @family, method: :delete, data: { confirm: 'Are you sure?' }, data: { tooltip: 'tooltip' }, class: "btn btn-default", title: "Delete" do %>
	          	<span class="glyphicon glyphicon-trash"></span>
	        <% end %>
		</div>    
	</div>
	<div class="panel-body">

		<%= render 'form' %>

	</div>
</div>

web/app/views/families/index.html.erb
<h1>Listing families</h1>
<hr>

<div class="panel panel-default">
  <div class="panel-heading panel-heading-toolbox">
    <div class="panel-toolbar">
      <%= link_to new_family_path, class: "btn btn-primary", data: { tooltip: 'tooltip' }, title: "New Family" do %>
        <span class="glyphicon glyphicon-plus"></span>
      <% end %>
    </div>    
  </div>
  <div class="panel-body">
    <table class="table table-hover">
      <thead>
        <tr>
                      <th>Name</th>
                      <th>Description</th>
                  </tr>
      </thead>

      <tbody>
        <% @families.each do |family| %>
          <tr>
                              <td><%= link_to family.name, family_path(family) %></td>
                              <td><%= family.description %></td>
                      </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="panel-footer panel-footer-toolbox">
    <div class="panel-toolbar">
      <%= will_paginate @families, renderer: BootstrapPagination::Rails %>
    </div>
  </div>
</div>

<br>

web/app/views/families/new.html.erb
<h1>New family</h1>
<hr>

<div class="panel panel-default">
	<div class="panel-heading panel-heading-toolbox">
		<div class="panel-toolbar">
			<%= link_to 'Volver', families_path, :class => "btn btn-link" %>
		</div>    
	</div>
	<div class="panel-body">

		<%= render 'form' %>

	</div>
</div>

web/app/views/families/show.html.erb
<h1>Detail family</h1>
<hr>

<div class="panel panel-default">
	<div class="panel-heading panel-heading-toolbox">
		<div class="panel-toolbar">
			<%= link_to 'Volver', families_path, :class => "btn btn-link" %>
			<%= link_to edit_family_path(@family), data: { tooltip: 'tooltip' }, class: "btn btn-default", title: "Edit" do %>
	          	<span class="glyphicon glyphicon-pencil"></span>
	        <% end %>
			<%= link_to @family, method: :delete, data: { confirm: 'Are you sure?' }, data: { tooltip: 'tooltip' }, class: "btn btn-default", title: "Delete" do %>
	          	<span class="glyphicon glyphicon-trash"></span>
	        <% end %>
		</div>    
	</div>
	<div class="panel-body">
		
		<table class="table table-bordered">
			<tbody>
							<tr>
				  <th>Name:</th>
				  <td><%= @family.name %></td>
				</tr>
							<tr>
				  <th>Description:</th>
				  <td><%= @family.description %></td>
				</tr>
						</tbody>
		</table>

	</div>
</div>