app-rails/config/routes.rb
Tut1::Application.routes.draw do
  
  resources :families

  resources :products

  resources :discounts

  resources :sales

  resources :detail_sales

  get "index/home"

  root 'index#home'

  devise_for :users, path: '',
    path_names: {
      sign_in: 'login',
      sign_out: 'logout',
      password: 'reset_password'
    }
  get "users" => "users#index"
  get "profile" => "users#show", as: "current_user"
  get "profile/edit" => "users#edit", as: "edit_current_user"
  patch "profile" => "users#update", as: "user"

  namespace :api, defaults: {format: :json} do
    namespace :v1 do 

      post 'products/:id', to: 'products#create'
      get 'products/:id', to: 'products#show'
      get 'products', to: 'products#index'
      put 'products/:id', to: 'products#update'

      post 'discounts/:id', to: 'discounts#create'
      get 'discounts/:id', to: 'discounts#show'
      get 'discounts', to: 'discounts#index'
      put 'discounts/:id', to: 'discounts#update'

      post 'sales/:id', to: 'sales#create'
      get 'sales/:id', to: 'sales#show'
      get 'sales', to: 'sales#index'
      put 'sales/:id', to: 'sales#update'

      post 'detail_sales/:id', to: 'detail_sales#create'
      get 'detail_sales/:id', to: 'detail_sales#show'
      get 'detail_sales', to: 'detail_sales#index'
      put 'detail_sales/:id', to: 'detail_sales#update'
    end 
  end
  

end

app-rails/app/models/sale.rb
class Sale < ActiveRecord::Base
	include Filterable
	include Importable
	include Exportable

	self.per_page = 10

		
	# Validations
			# validates :name, <validations>
			# validates :description, <validations>
			# validates :total, <validations>
	
	# Scopes (used for search form)
	#   To search by full text use { where("attribute like ?", "%#{attribute}%") }
	#   To search by string use { where attribute: attribute }
		scope :byname, -> (name) { where("name like ?", "%#{name}%") }
		scope :description, -> (description) { where description: description }
		scope :total, -> (total) { where total: total }
	
end

app-rails/app/controllers/api/v1/sales_controller.rb
class Api::V1::SalesController < Api::V1::ApplicationController

  before_action :set_sale, only: [:show, :edit, :update, :destroy]

  # GET /sales
  def index
    @sales = Sale.all
  end

  # GET /sales/1
  def show
  end

  # GET /sales/new
  def new
    @sale = Sale.new
  end

  # GET /sales/1/edit
  def edit
  end

  # POST /sales
  def create
    @sale = Sale.new(sale_params)

    if @sale.save
      redirect_to @sale, notice: 'Sale was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /sales/1
  def update
    if @sale.update(sale_params)
      redirect_to @sale, notice: 'Sale was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /sales/1
  def destroy
    @sale.destroy
    redirect_to sales_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def sale_params
      params.require(:sale).permit(:name, :description, :total)
    end
end

app-rails/app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: [:show, :edit, :update, :destroy]

  # GET /sales
  def index
    @sales = Sale.paginate(:page => params[:page])
  end

  # GET /sales/1
  def show
  end

  # GET /sales/new
  def new
    @sale = Sale.new
  end

  # GET /sales/1/edit
  def edit
  end

  # POST /sales
  def create
    @sale = Sale.new(sale_params)

    if @sale.save
      redirect_to @sale, notice: 'Sale was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /sales/1
  def update
    if @sale.update(sale_params)
      redirect_to @sale, notice: 'Sale was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /sales/1
  def destroy
    @sale.destroy
    redirect_to sales_url, notice: 'Sale was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def sale_params
      params.require(:sale).permit(:name, :description, :total)
    end
end

app-rails/app/helpers/sales_helper.rb
module SalesHelper
end

app-rails/app/views/sales/_form.html.erb
<%= form_for(@sale) do |f| %>
<% if @sale.errors.any? %>
<div id="error_explanation">
    <h2><%= pluralize(@sale.errors.count, "error") %> prohibited this sale from being saved:</h2>

    <ul>
        <% @sale.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
    </ul>
</div>
<% end %>

<div class="form-group">
                <%= f.label :name %>
            <%= f.text_field :name, :class => "form-control" %>
    </div>
<div class="form-group">
                <%= f.label :description %>
            <%= f.text_field :description, :class => "form-control" %>
    </div>
<div class="form-group">
                <%= f.label :total %>
            <%= f.number_field :total, :class => "form-control" %>
    </div>
<div class="actions">
    <%= f.submit :class => "btn btn-success" %>
</div>
<% end %>

app-rails/app/views/sales/edit.html.erb
<h1>Editing sale</h1>
<hr>

<div class="panel panel-default">
	<div class="panel-heading panel-heading-toolbox">
		<div class="panel-toolbar">
			<%= link_to 'Volver', sales_path, :class => "btn btn-link" %>
			<%= link_to @sale, method: :delete, data: { confirm: 'Are you sure?' }, data: { tooltip: 'tooltip' }, class: "btn btn-default", title: "Delete" do %>
	          	<span class="glyphicon glyphicon-trash"></span>
	        <% end %>
		</div>    
	</div>
	<div class="panel-body">

		<%= render 'form' %>

	</div>
</div>

app-rails/app/views/sales/index.html.erb
<h1>Listing sales</h1>
<hr>

<div class="panel panel-default">
  <div class="panel-heading panel-heading-toolbox">
    <div class="panel-toolbar">
      <%= link_to new_sale_path, class: "btn btn-primary", data: { tooltip: 'tooltip' }, title: "New Sale" do %>
        <span class="glyphicon glyphicon-plus"></span>
      <% end %>
    </div>    
  </div>
  <div class="panel-body">
    <table class="table table-hover">
      <thead>
        <tr>
                      <th>Name</th>
                      <th>Description</th>
                      <th>Total</th>
                  </tr>
      </thead>

      <tbody>
        <% @sales.each do |sale| %>
          <tr>
                              <td><%= link_to sale.name, sale_path(sale) %></td>
                              <td><%= sale.description %></td>
                              <td><%= sale.total %></td>
                      </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="panel-footer panel-footer-toolbox">
    <div class="panel-toolbar">
      <%= will_paginate @sales, renderer: BootstrapPagination::Rails %>
    </div>
  </div>
</div>

<br>

app-rails/app/views/sales/new.html.erb
<h1>New sale</h1>
<hr>

<div class="panel panel-default">
	<div class="panel-heading panel-heading-toolbox">
		<div class="panel-toolbar">
			<%= link_to 'Volver', sales_path, :class => "btn btn-link" %>
		</div>    
	</div>
	<div class="panel-body">

		<%= render 'form' %>

	</div>
</div>

app-rails/app/views/sales/show.html.erb
<h1>Detail sale</h1>
<hr>

<div class="panel panel-default">
	<div class="panel-heading panel-heading-toolbox">
		<div class="panel-toolbar">
			<%= link_to 'Volver', sales_path, :class => "btn btn-link" %>
			<%= link_to edit_sale_path(@sale), data: { tooltip: 'tooltip' }, class: "btn btn-default", title: "Edit" do %>
	          	<span class="glyphicon glyphicon-pencil"></span>
	        <% end %>
			<%= link_to @sale, method: :delete, data: { confirm: 'Are you sure?' }, data: { tooltip: 'tooltip' }, class: "btn btn-default", title: "Delete" do %>
	          	<span class="glyphicon glyphicon-trash"></span>
	        <% end %>
		</div>    
	</div>
	<div class="panel-body">
		
		<table class="table table-bordered">
			<tbody>
							<tr>
				  <th>Name:</th>
				  <td><%= @sale.name %></td>
				</tr>
							<tr>
				  <th>Description:</th>
				  <td><%= @sale.description %></td>
				</tr>
							<tr>
				  <th>Total:</th>
				  <td><%= @sale.total %></td>
				</tr>
						</tbody>
		</table>

	</div>
</div>