app-rails/config/routes.rb
Tut1::Application.routes.draw do
  
  resources :families

  resources :products

  resources :discounts

  resources :sales

  resources :detail_sales

  get "index/home"

  root 'index#home'

  devise_for :users, path: '',
    path_names: {
      sign_in: 'login',
      sign_out: 'logout',
      password: 'reset_password'
    }
  get "users" => "users#index"
  get "profile" => "users#show", as: "current_user"
  get "profile/edit" => "users#edit", as: "edit_current_user"
  patch "profile" => "users#update", as: "user"

  namespace :api, defaults: {format: :json} do
    namespace :v1 do 

      post 'products/:id', to: 'products#create'
      get 'products/:id', to: 'products#show'
      get 'products', to: 'products#index'
      put 'products/:id', to: 'products#update'

      post 'discounts/:id', to: 'discounts#create'
      get 'discounts/:id', to: 'discounts#show'
      get 'discounts', to: 'discounts#index'
      put 'discounts/:id', to: 'discounts#update'

      post 'sales/:id', to: 'sales#create'
      get 'sales/:id', to: 'sales#show'
      get 'sales', to: 'sales#index'
      put 'sales/:id', to: 'sales#update'

      post 'detail_sales/:id', to: 'detail_sales#create'
      get 'detail_sales/:id', to: 'detail_sales#show'
      get 'detail_sales', to: 'detail_sales#index'
      put 'detail_sales/:id', to: 'detail_sales#update'
    end 
  end
  

end

app-rails/app/models/product.rb
class Product < ActiveRecord::Base
	include Filterable
	include Importable
	include Exportable

	self.per_page = 10

	  		belongs_to :family
		
	# Validations
			# validates :barcode, <validations>
			# validates :brand, <validations>
			# validates :name, <validations>
			# validates :description, <validations>
			# validates :price, <validations>
			# validates :price_net, <validations>
			# validates :family, <validations>
	
	# Scopes (used for search form)
	#   To search by full text use { where("attribute like ?", "%#{attribute}%") }
	#   To search by string use { where attribute: attribute }
		scope :barcode, -> (barcode) { where barcode: barcode }
		scope :brand, -> (brand) { where brand: brand }
		scope :byname, -> (name) { where("name like ?", "%#{name}%") }
		scope :description, -> (description) { where description: description }
		scope :price, -> (price) { where price: price }
		scope :price_net, -> (price_net) { where price_net: price_net }
		scope :family, -> (family_name) { where("family.name like ?", "%#{family_name}%") }
	
end

app-rails/app/controllers/api/v1/products_controller.rb
class Api::V1::ProductsController < Api::V1::ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]


  # GET /products
  def index

    @products = Product.all
  end

  # GET /products/1
  def show
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to @product
    else
      render :json => "201", status:201
    end
  end

  # PATCH/PUT /products/1
  def update
    if @product.update(product_params)
      redirect_to @product
    else
      render :json => "201", status:201
    end
  end

  # DELETE /products/1
  def destroy
    @product.destroy
    redirect_to products_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def product_params
      params.require(:product).permit(:barcode, :brand, :name, :description, :price, :price_net, :family_id)
    end
end

app-rails/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  def index
    @products = Product.paginate(:page => params[:page])
  end

  # GET /products/1
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to @product, notice: 'Product was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /products/1
  def update
    if @product.update(product_params)
      redirect_to @product, notice: 'Product was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /products/1
  def destroy
    @product.destroy
    redirect_to products_url, notice: 'Product was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def product_params
      params.require(:product).permit(:barcode, :brand, :name, :description, :price, :price_net, :family_id)
    end
end

app-rails/app/helpers/products_helper.rb
module ProductsHelper
end

app-rails/app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
<% if @product.errors.any? %>
<div id="error_explanation">
    <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

    <ul>
        <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
    </ul>
</div>
<% end %>

<div class="form-group">
                <%= f.label :barcode %>
            <%= f.number_field :barcode, :class => "form-control" %>
    </div>
<div class="form-group">
                <%= f.label :brand %>
            <%= f.text_field :brand, :class => "form-control" %>
    </div>
<div class="form-group">
                <%= f.label :name %>
            <%= f.text_field :name, :class => "form-control" %>
    </div>
<div class="form-group">
                <%= f.label :description %>
            <%= f.text_field :description, :class => "form-control" %>
    </div>
<div class="form-group">
                <%= f.label :price %>
            <%= f.number_field :price, :class => "form-control" %>
    </div>
<div class="form-group">
                <%= f.label :price_net %>
            <%= f.number_field :price_net, :class => "form-control" %>
    </div>
<div class="form-group">
                <%= f.label :family_id %>
            <%= f.collection_select :family_id, Family.all, :id, :name, prompt: true, :class => 'form-control'  %>
    </div>
<div class="actions">
    <%= f.submit :class => "btn btn-success" %>
</div>
<% end %>

app-rails/app/views/products/edit.html.erb
<h1>Editing product</h1>
<hr>

<div class="panel panel-default">
	<div class="panel-heading panel-heading-toolbox">
		<div class="panel-toolbar">
			<%= link_to 'Volver', products_path, :class => "btn btn-link" %>
			<%= link_to @product, method: :delete, data: { confirm: 'Are you sure?' }, data: { tooltip: 'tooltip' }, class: "btn btn-default", title: "Delete" do %>
	          	<span class="glyphicon glyphicon-trash"></span>
	        <% end %>
		</div>    
	</div>
	<div class="panel-body">

		<%= render 'form' %>

	</div>
</div>

app-rails/app/views/products/index.html.erb
<h1>Listing products</h1>
<hr>

<div class="panel panel-default">
  <div class="panel-heading panel-heading-toolbox">
    <div class="panel-toolbar">
      <%= link_to new_product_path, class: "btn btn-primary", data: { tooltip: 'tooltip' }, title: "New Product" do %>
        <span class="glyphicon glyphicon-plus"></span>
      <% end %>
    </div>    
  </div>
  <div class="panel-body">
    <table class="table table-hover">
      <thead>
        <tr>
                      <th>Barcode</th>
                      <th>Brand</th>
                      <th>Name</th>
                      <th>Description</th>
                      <th>Price</th>
                      <th>Price net</th>
                      <th>Family</th>
                  </tr>
      </thead>

      <tbody>
        <% @products.each do |product| %>
          <tr>
                              <td><%= product.barcode %></td>
                              <td><%= product.brand %></td>
                              <td><%= link_to product.name, product_path(product) %></td>
                              <td><%= product.description %></td>
                              <td><%= product.price %></td>
                              <td><%= product.price_net %></td>
                            <td><%= product.family.name %></td>
                      </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="panel-footer panel-footer-toolbox">
    <div class="panel-toolbar">
      <%= will_paginate @products, renderer: BootstrapPagination::Rails %>
    </div>
  </div>
</div>

<br>

app-rails/app/views/products/new.html.erb
<h1>New product</h1>
<hr>

<div class="panel panel-default">
	<div class="panel-heading panel-heading-toolbox">
		<div class="panel-toolbar">
			<%= link_to 'Volver', products_path, :class => "btn btn-link" %>
		</div>    
	</div>
	<div class="panel-body">

		<%= render 'form' %>

	</div>
</div>

app-rails/app/views/products/show.html.erb
<h1>Detail product</h1>
<hr>

<div class="panel panel-default">
	<div class="panel-heading panel-heading-toolbox">
		<div class="panel-toolbar">
			<%= link_to 'Volver', products_path, :class => "btn btn-link" %>
			<%= link_to edit_product_path(@product), data: { tooltip: 'tooltip' }, class: "btn btn-default", title: "Edit" do %>
	          	<span class="glyphicon glyphicon-pencil"></span>
	        <% end %>
			<%= link_to @product, method: :delete, data: { confirm: 'Are you sure?' }, data: { tooltip: 'tooltip' }, class: "btn btn-default", title: "Delete" do %>
	          	<span class="glyphicon glyphicon-trash"></span>
	        <% end %>
		</div>    
	</div>
	<div class="panel-body">
		
		<table class="table table-bordered">
			<tbody>
							<tr>
				  <th>Barcode:</th>
				  <td><%= @product.barcode %></td>
				</tr>
							<tr>
				  <th>Brand:</th>
				  <td><%= @product.brand %></td>
				</tr>
							<tr>
				  <th>Name:</th>
				  <td><%= @product.name %></td>
				</tr>
							<tr>
				  <th>Description:</th>
				  <td><%= @product.description %></td>
				</tr>
							<tr>
				  <th>Price:</th>
				  <td><%= @product.price %></td>
				</tr>
							<tr>
				  <th>Price net:</th>
				  <td><%= @product.price_net %></td>
				</tr>
							<tr>
					<th>Family:</th>
					<td><%= @product.family.name %></td>
				</tr>
						</tbody>
		</table>

	</div>
</div>