app-rails/config/routes.rb
Tut1::Application.routes.draw do
  
  resources :families

  resources :products

  resources :discounts

  resources :sales

  resources :detail_sales

  get "index/home"

  root 'index#home'

  devise_for :users, path: '',
    path_names: {
      sign_in: 'login',
      sign_out: 'logout',
      password: 'reset_password'
    }
  get "users" => "users#index"
  get "profile" => "users#show", as: "current_user"
  get "profile/edit" => "users#edit", as: "edit_current_user"
  patch "profile" => "users#update", as: "user"

  namespace :api, defaults: {format: :json} do
    namespace :v1 do 

      post 'products/:id', to: 'products#create'
      get 'products/:id', to: 'products#show'
      get 'products', to: 'products#index'
      put 'products/:id', to: 'products#update'

      post 'discounts/:id', to: 'discounts#create'
      get 'discounts/:id', to: 'discounts#show'
      get 'discounts', to: 'discounts#index'
      put 'discounts/:id', to: 'discounts#update'

      post 'sales/:id', to: 'sales#create'
      get 'sales/:id', to: 'sales#show'
      get 'sales', to: 'sales#index'
      put 'sales/:id', to: 'sales#update'

      post 'detail_sales/:id', to: 'detail_sales#create'
      get 'detail_sales/:id', to: 'detail_sales#show'
      get 'detail_sales', to: 'detail_sales#index'
      put 'detail_sales/:id', to: 'detail_sales#update'
    end 
  end
  

end

app-rails/app/models/detail_sale.rb
class DetailSale < ActiveRecord::Base
	include Filterable
	include Importable
	include Exportable

	self.per_page = 10

	  		belongs_to :sale
	  		belongs_to :product
		
	# Validations
			# validates :name, <validations>
			# validates :quantity, <validations>
			# validates :valor, <validations>
			# validates :sale, <validations>
			# validates :product, <validations>
	
	# Scopes (used for search form)
	#   To search by full text use { where("attribute like ?", "%#{attribute}%") }
	#   To search by string use { where attribute: attribute }
		scope :byname, -> (name) { where("name like ?", "%#{name}%") }
		scope :quantity, -> (quantity) { where quantity: quantity }
		scope :valor, -> (valor) { where valor: valor }
		scope :sale, -> (sale_name) { where("sale.name like ?", "%#{sale_name}%") }
		scope :product, -> (product_name) { where("product.name like ?", "%#{product_name}%") }
	
end

app-rails/app/controllers/api/v1/detail_sales_controller.rb
class Api::V1::DetailSalesController < Api::V1::ApplicationController


  before_action :set_detail_sale, only: [:show, :edit, :update, :destroy]

  # GET /detail_sales
  def index
    @detail_sales = DetailSale.all
  end

  # GET /detail_sales/1
  def show
  end

  # GET /detail_sales/1/edit
  def edit
  end

  # POST /detail_sales
  def create
    @detail_sale = DetailSale.new(detail_sale_params)

    if @detail_sale.save
      redirect_to @detail_sale
    else
      render :json => "201", status:201
    end
  end

  # PATCH/PUT /detail_sales/1
  def update
    if @detail_sale.update(detail_sale_params)
      redirect_to @detail_sale
    else
      render :json => "201", status:201
    end
  end

  # DELETE /detail_sales/1
  def destroy
    @detail_sale.destroy
    redirect_to detail_sales_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_detail_sale
      @detail_sale = DetailSale.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def detail_sale_params
      params.require(:detail_sale).permit(:name, :quantity, :valor, :sale_id, :product_id)
    end
end

app-rails/app/controllers/detail_sales_controller.rb
class DetailSalesController < ApplicationController
  before_action :set_detail_sale, only: [:show, :edit, :update, :destroy]

  # GET /detail_sales
  def index
    @detail_sales = DetailSale.paginate(:page => params[:page])
  end

  # GET /detail_sales/1
  def show
  end

  # GET /detail_sales/new
  def new
    @detail_sale = DetailSale.new
  end

  # GET /detail_sales/1/edit
  def edit
  end

  # POST /detail_sales
  def create
    @detail_sale = DetailSale.new(detail_sale_params)

    if @detail_sale.save
      redirect_to @detail_sale, notice: 'Detail sale was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /detail_sales/1
  def update
    if @detail_sale.update(detail_sale_params)
      redirect_to @detail_sale, notice: 'Detail sale was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /detail_sales/1
  def destroy
    @detail_sale.destroy
    redirect_to detail_sales_url, notice: 'Detail sale was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_detail_sale
      @detail_sale = DetailSale.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def detail_sale_params
      params.require(:detail_sale).permit(:name, :quantity, :valor, :sale_id, :product_id)
    end
end

app-rails/app/helpers/detail_sales_helper.rb
module DetailSalesHelper
end

app-rails/app/views/detail_sales/_form.html.erb
<%= form_for(@detail_sale) do |f| %>
<% if @detail_sale.errors.any? %>
<div id="error_explanation">
    <h2><%= pluralize(@detail_sale.errors.count, "error") %> prohibited this detail_sale from being saved:</h2>

    <ul>
        <% @detail_sale.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
    </ul>
</div>
<% end %>

<div class="form-group">
                <%= f.label :name %>
            <%= f.text_field :name, :class => "form-control" %>
    </div>
<div class="form-group">
                <%= f.label :quantity %>
            <%= f.number_field :quantity, :class => "form-control" %>
    </div>
<div class="form-group">
                <%= f.label :valor %>
            <%= f.number_field :valor, :class => "form-control" %>
    </div>
<div class="form-group">
                <%= f.label :sale_id %>
            <%= f.collection_select :sale_id, Sale.all, :id, :name, prompt: true, :class => 'form-control'  %>
    </div>
<div class="form-group">
                <%= f.label :product_id %>
            <%= f.collection_select :product_id, Product.all, :id, :name, prompt: true, :class => 'form-control'  %>
    </div>
<div class="actions">
    <%= f.submit :class => "btn btn-success" %>
</div>
<% end %>

app-rails/app/views/detail_sales/edit.html.erb
<h1>Editing detail_sale</h1>
<hr>

<div class="panel panel-default">
	<div class="panel-heading panel-heading-toolbox">
		<div class="panel-toolbar">
			<%= link_to 'Volver', detail_sales_path, :class => "btn btn-link" %>
			<%= link_to @detail_sale, method: :delete, data: { confirm: 'Are you sure?' }, data: { tooltip: 'tooltip' }, class: "btn btn-default", title: "Delete" do %>
	          	<span class="glyphicon glyphicon-trash"></span>
	        <% end %>
		</div>    
	</div>
	<div class="panel-body">

		<%= render 'form' %>

	</div>
</div>

app-rails/app/views/detail_sales/index.html.erb
<h1>Listing detail_sales</h1>
<hr>

<div class="panel panel-default">
  <div class="panel-heading panel-heading-toolbox">
    <div class="panel-toolbar">
      <%= link_to new_detail_sale_path, class: "btn btn-primary", data: { tooltip: 'tooltip' }, title: "New Detail sale" do %>
        <span class="glyphicon glyphicon-plus"></span>
      <% end %>
    </div>    
  </div>
  <div class="panel-body">
    <table class="table table-hover">
      <thead>
        <tr>
                      <th>Name</th>
                      <th>Quantity</th>
                      <th>Valor</th>
                      <th>Sale</th>
                      <th>Product</th>
                  </tr>
      </thead>

      <tbody>
        <% @detail_sales.each do |detail_sale| %>
          <tr>
                              <td><%= link_to detail_sale.name, detail_sale_path(detail_sale) %></td>
                              <td><%= detail_sale.quantity %></td>
                              <td><%= detail_sale.valor %></td>
                            <td><%= detail_sale.sale.name %></td>
                            <td><%= detail_sale.product.name %></td>
                      </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="panel-footer panel-footer-toolbox">
    <div class="panel-toolbar">
      <%= will_paginate @detail_sales, renderer: BootstrapPagination::Rails %>
    </div>
  </div>
</div>

<br>

app-rails/app/views/detail_sales/new.html.erb
<h1>New detail_sale</h1>
<hr>

<div class="panel panel-default">
	<div class="panel-heading panel-heading-toolbox">
		<div class="panel-toolbar">
			<%= link_to 'Volver', detail_sales_path, :class => "btn btn-link" %>
		</div>    
	</div>
	<div class="panel-body">

		<%= render 'form' %>

	</div>
</div>

app-rails/app/views/detail_sales/show.html.erb
<h1>Detail detail_sale</h1>
<hr>

<div class="panel panel-default">
	<div class="panel-heading panel-heading-toolbox">
		<div class="panel-toolbar">
			<%= link_to 'Volver', detail_sales_path, :class => "btn btn-link" %>
			<%= link_to edit_detail_sale_path(@detail_sale), data: { tooltip: 'tooltip' }, class: "btn btn-default", title: "Edit" do %>
	          	<span class="glyphicon glyphicon-pencil"></span>
	        <% end %>
			<%= link_to @detail_sale, method: :delete, data: { confirm: 'Are you sure?' }, data: { tooltip: 'tooltip' }, class: "btn btn-default", title: "Delete" do %>
	          	<span class="glyphicon glyphicon-trash"></span>
	        <% end %>
		</div>    
	</div>
	<div class="panel-body">
		
		<table class="table table-bordered">
			<tbody>
							<tr>
				  <th>Name:</th>
				  <td><%= @detail_sale.name %></td>
				</tr>
							<tr>
				  <th>Quantity:</th>
				  <td><%= @detail_sale.quantity %></td>
				</tr>
							<tr>
				  <th>Valor:</th>
				  <td><%= @detail_sale.valor %></td>
				</tr>
							<tr>
					<th>Sale:</th>
					<td><%= @detail_sale.sale.name %></td>
				</tr>
							<tr>
					<th>Product:</th>
					<td><%= @detail_sale.product.name %></td>
				</tr>
						</tbody>
		</table>

	</div>
</div>